services:

    sonata.admin.post:
        class: AppBundle\Admin\User
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "User" }
        arguments:
            - ~
            - AppBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]

    sonata.admin.question:
        class: AppBundle\Admin\Question
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Questions", label: "Question" }
        arguments:
            - ~
            - AppBundle\Entity\Question
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]