parameters:
    basic.teams.names:
        - Ninjas
        - Power rangers
        - Avengers
        - The detectives
        - Brainstorms
        - El Diablos
        - The Walkie Talkies
        - French Toast Mafia
        - Victorious Secret
        - Here for Beer
        - The Cereal Killers
        - Kung Fu Pandas
        - Smooth Operators
        - F.B.I.
        - "CSI: Miami"
        - Predators
        - Toxic Sushi
        - The Flaming Pink Flamingos
        - Wolverines
        - The X-men
        - Chocolate Orange Penguins
        - Red Hot Trivia Peppers
        - The Party Crashers
        - Moon Walkers
        - Time-Travellers
        - Delta Ducks
        - "It's Business Time"
        - Banana Splits
        - The Pirates
        - Cowboys
        - The Lanisters
        - The Starks
        - Black Crows

    basic.teams.size: 5

services:
    basic.encryptor:
        class: AppBundle\Encryptor\AES256Encryptor
        arguments:
            - %secret%

    basic.users:
        class: AppBundle\Service\Users
        arguments:
            - @fos_user.user_manager.default
            - @fos_user.mailer.default
            - %kernel.root_dir%
            - %url%

    basic.teams.name_generator:
        class: AppBundle\Teams\TeamNameGenerator
        calls:
            - [setNames, [%basic.teams.names%]]

    basic.teams.generator:
        class: AppBundle\Teams\Generator
        arguments:
            - @doctrine.orm.entity_manager
        calls:
            - [setTeamNameGenerator, [@basic.teams.name_generator]]
            - [setTeamSize, [%basic.teams.size%]]

    basic.api:
        class: AppBundle\Service\Api
        arguments:
            - @doctrine.orm.entity_manager

    fos_user.change_password.form.type:
        class: AppBundle\Form\ChangePasswordFormType
        tags:
            - { name: form.type, alias: fos_user_change_password }

