parameters:
    basic.teams.names:
        - Ninjas
        - Power rangers
        - Avengers
        - The detectives
        - Brainstorms

    basic.teams.size: 5

services:
    basic.encryptor:
        class: AppBundle\Encryptor\AES256Encryptor
        arguments:
            - %secret%

    basic.users:
        class: AppBundle\Service\Users
        arguments:
          - @fos_user.user_manager.default

    basic.teams.name_generator:
        class: AppBundle\Teams\TeamNameGenerator
        calls:
            - [setNames, [%basic.teams.names%]]

    basic.teams.generator:
        class: AppBundle\Teams\Generator
        calls:
            - [setTeamNameGenerator, [@basic.teams.name_generator]]
            - [setTeamSize, [%basic.teams.size%]]

    sonata.admin.post:
        class: AppBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "User" }
        arguments:
            - ~
            - AppBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]