parameters:
    basic.teams.names:
        - Ninjas
        - Power rangers
        - Avengers
        - The detectives
        - Brainstorms

    basic.teams.size: 5

services:
    basic.encryptor:
        class: AppBundle\Encryptor\AES256Encryptor
        arguments:
            - %secret%

    basic.users:
        class: AppBundle\Service\Users
        arguments:
            - @fos_user.user_manager.default
            - @fos_user.mailer.default
            - %kernel.root_dir%
            - %url%

    basic.teams.name_generator:
        class: AppBundle\Teams\TeamNameGenerator
        calls:
            - [setNames, [%basic.teams.names%]]

    basic.teams.generator:
        class: AppBundle\Teams\Generator
        calls:
            - [setTeamNameGenerator, [@basic.teams.name_generator]]
            - [setTeamSize, [%basic.teams.size%]]
    
    fos_user.change_password.form.type:
        class: AppBundle\Form\ChangePasswordFormType
        tags:
            - { name: form.type, alias: fos_user_change_password }
